[package]
name = "wasm"
version = "0.1.0"
authors = ["Seven <askdaddy@gmail.com>"]
edition = "2018"

[dependencies]
wasm-bindgen = "0.2.79"
js-sys = "0.3"

[dependencies.web-sys]
version = "0.3.4"
features = [
    'Performance'
]

[lib]
crate-type = ["cdylib"]
path = "./src/wasm/lib.rs"
